Namespace(batch_size=2000, cpuonly=False, dataset='imagenet', downloadall=False, end=10000, freeze=True, freeze_idx=25, manual_split=False, model='vgg11', num_epochs=1, sequential=False, split_idx=100, start=0, testonly=False, use_intermediate=False)
==> Preparing data..
==> Building model..
Using split index: 100
Freezing the lower layers of the model (vgg11) till index 25
The mode is:  vanilla
Memory occpied: (1762.0, 3.0)
Memory occpied: (1762.0, 3.0)
Memory occpied: (1762.0, 3.0)
Memory occpied: (1762.0, 3.0)
Memory occpied: (1762.0, 3.0)
Read 252.732816696167 MBs for this batch
Streaming imagenet data took 6.479304790496826 seconds
The mode is:  vanilla

Epoch: 0
Memory occpied: (1762.0, 3.0)
Memory occpied: (1762.0, 3.0)
Memory occpied: (1762.0, 3.0)
Memory occpied: (1762.0, 3.0)
Memory occpied: (1762.0, 3.0)
Memory occpied: (1762.0, 3.0)
Time of next(dataloader) is: 6.7466840744018555
Memory occpied: (1762.0, 3.0)
Read 244.98475742340088 MBs for this batch
Streaming imagenet data took 6.880899906158447 seconds
Time for copying to cuda: 0.2950587272644043
Memory occpied: (2912.0, 1030.0)
Memory occpied: (2912.0, 1534.0)
Memory occpied: (2912.0, 15032.0)
Exception: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/vgg.py", line 66, in forward
    x = self.features(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 11.96 GiB (GPU 0; 14.76 GiB total capacity; 1.62 GiB already allocated; 11.91 GiB free; 1.62 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

The whole process took 24.942259788513184 seconds
