Namespace(all_in_cos=False, batch_size=2000, cached=True, cpuonly=False, dataset='imagenet', downloadall=False, end=10000, freeze=True, freeze_idx=17, model='vit', num_epochs=1, sequential=False, split_choice='automatic', split_idx=100, start=0, testonly=False, transformed=True, use_intermediate=False)
Nb GPUS  2
==> Preparing data..
==> Building model..
Using split index: 100
Freezing the lower layers of the model (vit) till index 17
The mode is:  vanilla
Start 0, end 2000, post_step 1000

Memory occpied: (1630.0, 3.0)
Memory occpied: (1630.0, 3.0)
Memory occpied: (1630.0, 3.0)
Memory occpied: (1630.0, 3.0)
Decompress data took 0.09901070594787598 seconds
Memory occpied: (1630.0, 3.0)
Memory occpied: (1630.0, 3.0)
Total decompress data took 2.7928264141082764 seconds
Decompress data took 0.10312485694885254 seconds
Memory occpied: (1630.0, 3.0)
Memory occpied: (1630.0, 3.0)
Total decompress data took 2.792085886001587 seconds
Read 308.89431381225586 MBs for this batch
Memory occpied: (1630.0, 3.0)
Streaming imagenet data took 9.890411615371704 seconds
The mode is:  vanilla
Start 2000, end 4000, post_step 1000


Epoch: 0
Time of next(dataloader) is: 0.9553022384643555
Memory occpied: (1630.0, 3.0)
Time for copying to cuda: 0.31253576278686523
Memory occpied: (2780.0, 932.0)
Decompress data took 0.10085248947143555 seconds
Memory occpied: (2780.0, 1374.0)
Memory occpied: (2780.0, 2128.0)
Memory occpied: (13866.0, 6222.0)
Total decompress data took 2.9512853622436523 seconds
Decompress data took 0.10313940048217773 seconds
Exception: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timm/models/vision_transformer.py", line 433, in forward
    x = self.forward_features(x)
  File "/usr/local/lib/python3.8/dist-packages/timm/models/vision_transformer.py", line 421, in forward_features
    x = self.blocks(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timm/models/vision_transformer.py", line 238, in forward
    x = x + self.drop_path1(self.ls1(self.attn(self.norm1(x))))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timm/models/vision_transformer.py", line 199, in forward
    attn = (q @ k.transpose(-2, -1)) * self.scale
RuntimeError: CUDA out of memory. Tried to allocate 1.74 GiB (GPU 0; 14.76 GiB total capacity; 12.21 GiB already allocated; 1.21 GiB free; 12.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Memory occpied: (13872.0, 15038.0)
The whole process took 23.815075635910034 seconds
Total decompress data took 2.839292049407959 seconds
Read 306.5873851776123 MBs for this batch
Streaming imagenet data took 9.199692964553833 seconds
