Namespace(batch_size=500, cpuonly=False, dataset='imagenet', downloadall=False, end=10000, freeze=True, freeze_idx=21, manual_split=False, model='resnet50', num_epochs=1, sequential=False, split_idx=100, start=0, testonly=False, use_intermediate=False)
==> Preparing data..
==> Building model..
Using split index: 100
Freezing the lower layers of the model (resnet50) till index 21
Memory occpied: (6331.0, 3.0)
Memory occpied: (6989.0, 3.0)
Memory occpied: (8171.0, 3.0)
Memory occpied: (8171.0, 3.0)
Read 62.80299091339111 MBs for this batch
Streaming imagenet data took 4.214199542999268 seconds

Epoch: 0
Memory occpied: (8171.0, 3.0)
Memory occpied: (8171.0, 3.0)
Time of next(dataloader) is: 3.195648431777954
Time for copying to cuda: 0.08676695823669434
Memory occpied: (9323.0, 617.0)
Memory occpied: (9611.0, 1662.0)
Memory occpied: (9899.0, 3171.0)
Read 65.439866065979 MBs for this batch
Streaming imagenet data took 6.722484827041626 seconds
Memory occpied: (9899.0, 5161.0)
Memory occpied: (15023.0, 14025.0)
Memory occpied: (13966.0, 14942.0)
Memory occpied: (14828.0, 13788.0)
Memory occpied: (14274.0, 12812.0)
Memory occpied: (13269.0, 11889.0)
Memory occpied: (7206.0, 14094.0)
Exception: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/resnet.py", line 249, in forward
    return self._forward_impl(x)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/resnet.py", line 232, in _forward_impl
    x = self.conv1(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 766.00 MiB (GPU 0; 14.76 GiB total capacity; 385.73 MiB already allocated; 112.75 MiB free; 406.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Memory occpied: (7206.0, 13506.0)
The whole process took 27.525837898254395 seconds
