Namespace(batch_size=2000, cpuonly=False, dataset='imagenet', downloadall=False, end=10000, freeze=True, freeze_idx=17, manual_split=False, model='alexnet', num_epochs=1, sequential=False, split_idx=100, start=0, testonly=False, use_intermediate=False)
==> Preparing data..
==> Building model..
Using split index: 100
Freezing the lower layers of the model (alexnet) till index 17
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Read 254.37291526794434 MBs for this batch
Streaming imagenet data took 18.356054306030273 seconds

Epoch: 0
Time of next(dataloader) is: 10.865585803985596
Time for copying to cuda: 0.4485330581665039
Read 246.17637538909912 MBs for this batch
Streaming imagenet data took 23.32991051673889 seconds
Exception: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/alexnet.py", line 46, in forward
    x = self.features(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 740.00 MiB (GPU 0; 14.76 GiB total capacity; 1.35 GiB already allocated; 352.75 MiB free; 1.36 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Memory occpied: (8085.0, 14837.0)
The whole process took 49.95961284637451 seconds
