Namespace(batch_size=2000, cpuonly=False, dataset='imagenet', downloadall=False, end=10000, freeze=True, freeze_idx=21, model='resnet50', num_epochs=1, sequential=False, split_choice='automatic', split_idx=100, start=0, testonly=False, use_intermediate=False)
==> Preparing data..
==> Building model..
Using split index: 100
Freezing the lower layers of the model (resnet50) till index 21
The mode is:  vanilla
Start 0, end 2000, post_step 1000

Memory occpied: (1366.0, 3.0)
Memory occpied: (1366.0, 3.0)
Memory occpied: (1366.0, 3.0)
Memory occpied: (1366.0, 3.0)
Memory occpied: (1366.0, 3.0)
Memory occpied: (1366.0, 3.0)
Memory occpied: (1366.0, 3.0)
Memory occpied: (1366.0, 3.0)
Read 308.89431381225586 MBs for this batch
Memory occpied: (1366.0, 3.0)
Streaming imagenet data took 9.524792909622192 seconds
The mode is:  vanilla
Start 2000, end 4000, post_step 1000


Epoch: 0
Time of next(dataloader) is: 0.8909134864807129
Memory occpied: (2516.0, 3.0)
Time for copying to cuda: 0.38121724128723145
Memory occpied: (2516.0, 972.0)
Memory occpied: (2516.0, 1354.0)
Memory occpied: (2516.0, 1766.0)
Memory occpied: (12654.0, 12042.0)
Memory occpied: (13718.0, 12042.0)
Memory occpied: (2528.0, 15106.0)
Read 306.5873851776123 MBs for this batch
Streaming imagenet data took 9.032728433609009 seconds
Memory occpied: (2528.0, 12042.0)
Memory occpied: (2528.0, 12424.0)
Memory occpied: (2528.0, 12424.0)
Memory occpied: (2528.0, 8982.0)
Memory occpied: (2528.0, 8216.0)
Memory occpied: (2528.0, 13554.0)
Memory occpied: (2528.0, 11578.0)
Memory occpied: (2528.0, 11578.0)
Exception: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/resnet.py", line 283, in forward
    return self._forward_impl(x)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/resnet.py", line 271, in _forward_impl
    x = self.layer1(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/resnet.py", line 156, in forward
    identity = self.downsample(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py", line 2421, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 2.99 GiB (GPU 0; 14.76 GiB total capacity; 7.95 GiB already allocated; 1.36 GiB free; 12.17 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

The whole process took 33.25688457489014 seconds
