Namespace(batch_size=500, cpuonly=False, dataset='imagenet', downloadall=False, end=10000, freeze=True, freeze_idx=36, manual_split=False, model='vgg19', num_epochs=1, sequential=False, split_idx=100, start=0, testonly=False, use_intermediate=False)
==> Preparing data..
==> Building model..
Using split index: 100
Freezing the lower layers of the model (vgg19) till index 36
Memory occpied: (8171.0, 3.0)
Memory occpied: (8171.0, 3.0)
Memory occpied: (8171.0, 3.0)
Memory occpied: (8171.0, 3.0)
Read 62.80299091339111 MBs for this batch
Streaming imagenet data took 4.581125736236572 seconds

Epoch: 0
Memory occpied: (8171.0, 3.0)
Memory occpied: (9323.0, 1001.0)
Time of next(dataloader) is: 3.2195401191711426
Time for copying to cuda: 0.13923978805541992
Memory occpied: (9899.0, 2084.0)
Memory occpied: (9899.0, 3675.0)
Memory occpied: (9899.0, 5931.0)
Read 65.439866065979 MBs for this batch
Streaming imagenet data took 6.5793375968933105 seconds
Memory occpied: (13237.0, 13041.0)
Memory occpied: (14504.0, 14594.0)
Memory occpied: (13608.0, 12580.0)
Exception: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/vgg.py", line 49, in forward
    x = self.features(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 2.99 GiB (GPU 0; 14.76 GiB total capacity; 3.81 GiB already allocated; 2.08 GiB free; 3.83 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Memory occpied: (13462.0, 13800.0)
The whole process took 23.875366687774658 seconds
