Namespace(batch_size=2000, cpuonly=False, dataset='imagenet', downloadall=False, end=10000, freeze=True, freeze_idx=36, manual_split=False, model='vgg19', num_epochs=1, sequential=False, split_idx=100, start=0, testonly=False, use_intermediate=False)
==> Preparing data..
==> Building model..
Using split index: 100
Freezing the lower layers of the model (vgg19) till index 36
The mode is:  vanilla
Memory occpied: (1822.0, 3.0)
Memory occpied: (1822.0, 3.0)
Memory occpied: (1822.0, 3.0)
Memory occpied: (1822.0, 3.0)
Memory occpied: (1822.0, 3.0)
Memory occpied: (1822.0, 3.0)
Read 252.732816696167 MBs for this batch
Streaming imagenet data took 6.637155532836914 seconds
The mode is:  vanilla

Epoch: 0
Memory occpied: (1822.0, 3.0)
Memory occpied: (1822.0, 3.0)
Memory occpied: (1822.0, 3.0)
Memory occpied: (1822.0, 3.0)
Memory occpied: (1822.0, 3.0)
Time of next(dataloader) is: 6.683018684387207
Read 244.98475742340088 MBs for this batch
Streaming imagenet data took 6.907738447189331 seconds
Time for copying to cuda: 0.29871678352355957
Memory occpied: (2972.0, 934.0)
Memory occpied: (2972.0, 1440.0)
Memory occpied: (3408.0, 15076.0)
Exception: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/vgg.py", line 66, in forward
    x = self.features(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 11.96 GiB (GPU 0; 14.76 GiB total capacity; 1.66 GiB already allocated; 11.85 GiB free; 1.68 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

The whole process took 24.950942277908325 seconds
