Namespace(batch_size=2000, cpuonly=False, dataset='imagenet', downloadall=False, end=10000, freeze=True, freeze_idx=17, manual_split=False, model='vit', num_epochs=1, sequential=False, split_idx=100, start=0, testonly=False, use_intermediate=False)
==> Preparing data..
==> Building model..
Using split index: 100
Freezing the lower layers of the model (vit) till index 17
The mode is:  vanilla
Memory occpied: (1630.0, 3.0)
Memory occpied: (1630.0, 3.0)
Memory occpied: (1630.0, 3.0)
Memory occpied: (1630.0, 3.0)
Memory occpied: (1630.0, 3.0)
Memory occpied: (1630.0, 3.0)
Read 252.732816696167 MBs for this batch
Streaming imagenet data took 6.421505451202393 seconds
The mode is:  vanilla

Epoch: 0
Memory occpied: (1630.0, 3.0)
Memory occpied: (1630.0, 3.0)
Memory occpied: (1630.0, 3.0)
Memory occpied: (1630.0, 3.0)
Memory occpied: (1630.0, 3.0)
Time of next(dataloader) is: 6.72868013381958
Read 244.98475742340088 MBs for this batch
Streaming imagenet data took 6.756597518920898 seconds
Time for copying to cuda: 0.29169559478759766
Memory occpied: (2780.0, 850.0)
Memory occpied: (2780.0, 1334.0)
Memory occpied: (2780.0, 1822.0)
Memory occpied: (13866.0, 7386.0)
Exception: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timm/models/vision_transformer.py", line 433, in forward
    x = self.forward_features(x)
  File "/usr/local/lib/python3.8/dist-packages/timm/models/vision_transformer.py", line 421, in forward_features
    x = self.blocks(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timm/models/vision_transformer.py", line 238, in forward
    x = x + self.drop_path1(self.ls1(self.attn(self.norm1(x))))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timm/models/vision_transformer.py", line 199, in forward
    attn = (q @ k.transpose(-2, -1)) * self.scale
RuntimeError: CUDA out of memory. Tried to allocate 1.74 GiB (GPU 0; 14.76 GiB total capacity; 12.21 GiB already allocated; 1.21 GiB free; 12.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Memory occpied: (13872.0, 15038.0)
The whole process took 26.42269253730774 seconds
