Namespace(batch_size=4000, cpuonly=False, dataset='inaturalist', downloadall=False, end=10000, freeze=True, freeze_idx=21, model='resnet50', num_epochs=1, sequential=False, split_choice='automatic', split_idx=100, start=0, testonly=False, use_intermediate=False)
==> Preparing data..
==> Building model..
Using split index: 100
Freezing the lower layers of the model (resnet50) till index 21
The mode is:  vanilla
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Read 1056.3339109420776 MBs for this batch
Streaming inaturalist data took 21.768875122070312 seconds
The mode is:  vanilla

Epoch: 0
Time of next(dataloader) is: 17.62977933883667
Time for copying to cuda: 0.5893094539642334
Read 1077.8234357833862 MBs for this batch
Streaming inaturalist data took 20.81273889541626 seconds
Exception: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/resnet.py", line 283, in forward
    return self._forward_impl(x)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/resnet.py", line 267, in _forward_impl
    x = self.bn1(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py", line 2421, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 5.98 GiB (GPU 0; 14.76 GiB total capacity; 8.38 GiB already allocated; 5.12 GiB free; 8.40 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Memory occpied: (1430.0, 14824.0)
The whole process took 54.234885454177856 seconds
